export interface Resources { cpus:number; memoryMib:number; diskGib:number }
export interface StorageSelection { id?:string; expectedVolumeId?:string; directory:string; allocationGib:number }
export interface StorageReviewOptions {deleteAll?:boolean;temporaryDirectory?:string;singleDiskGib?:number;restoreDisk?:string}
export interface StorageMaintenanceReview {kind:'resizeRemove'|'deleteAll'|'failureRecovery';backup:{directory:string;volumeId:string}|null;minimumGib:number;temporaryBytes:number;deletions:string[];downtime:string}
export interface StoragePlan { maintenance?:StorageMaintenanceReview|null; revision:number; locations:(StorageSelection & {id:string;volumeId:string})[]; totalGib:number; requiresRestart:boolean }
export interface StorageVolume { driveType?:string|null; suggestedDirectory?:string|null; id:string; label:string; mountPoint:string; filesystem:string; availableGib:number; configuredGib:number; eligible:boolean; reason:string }
export interface StorageLocation extends StorageSelection { id:string; volumeId:string; available:boolean; reason:string }
export interface StorageInventory {activeGib?:number;configuredGib?:number;recoveryEnabled?:boolean;disabled?:boolean;excluded?:StorageLocation[];recoveryBackup?:{path:string;bytes:number;verified:boolean}|null;backupCleanup?:{path:string;bytes:number}[]; systemDisk?:{directory:string;allocationGib:number}|null; defaultDirectory:string|null; supported:boolean; reason:string; volumes:StorageVolume[]; locations:StorageLocation[]; retainedCopies?:StorageLocation[]; revision?:number; operation?:{phase:string;message:string}|null }
export interface ScheduleWindow { days:number[]; startMinute:number; endMinute:number }
export interface Policy { enabled:boolean; resources:Resources; idleOnly:boolean; idleAfterMinutes:number; allowBattery:boolean; minBatteryPercent:number; scheduleEnabled:boolean; schedule:ScheduleWindow[]; startAtLogin:boolean; background:boolean; allowCi:boolean; allowServices:boolean; drainSeconds:number }
export interface Workload { name:string; namespace:string; state:string; cpu?:string; memory?:string }
export interface Snapshot { configuration?:ConfigurationReport; deviceId:string; name:string; platform:string; architecture:string; state:string; reason:string; policy:Policy; resources:Resources; storage?:StorageInventory; allocatedResources?:Resources|null; recreationPending?:boolean; workerReplacementAvailable?:boolean; worker:{installed:boolean;running:boolean}; enrolled:boolean; controllerUrl:string; version:string; workloads:Workload[] }
export interface Device { deviceId:string; name:string; platform:string; architecture:string; state:string; reason:string; lastSeen:string|null; eligibleCi:boolean; eligibleServices:boolean; allowCi?:boolean; allowServices?:boolean; remotePaused?:boolean; healthReason?:string; observedAt?:string|null; resources?:Resources; workloads?:Workload[] }
export type Action = 'prepare'|'resume'|'pause'|'stop';
export interface UpdateStatus { enabled:boolean; phase:string; message:string; currentVersion:string; availableVersion:string|null; downloaded:number; total:number|null }
export type UpdateAction = 'check'|'install'|'enable'|'disable'|'cancel';
export interface ActivityEntry { id:number; timestamp:string; level:string; source:string; message:string }
export interface ActivitySnapshot { entries:ActivityEntry[]; dropped:number; step:{message:string;startedAt:string;timeoutSeconds:number|null}|null }
export interface Backend { previewStorage?(locations:StorageSelection[],options?:StorageReviewOptions):Promise<StoragePlan>; setStorageRecovery?(enabled:boolean):Promise<Snapshot>; retryStorageMaintenance?():Promise<Snapshot>; applyStorage?(plan:StoragePlan):Promise<Snapshot>; chooseStorageDirectory?():Promise<string|null>; updates?():Promise<UpdateStatus>; updateAction?(action:UpdateAction):Promise<UpdateStatus>; mode?:'desktop'|'fleet'; snapshot():Promise<Snapshot>; activity?():Promise<ActivitySnapshot>; savePolicy(policy:Policy,expectedRevision?:number):Promise<Snapshot>; setRemoteConsent?(enabled:boolean):Promise<Snapshot>; configuration?(id:string):Promise<ConfigurationView>; configureDevice?(id:string,edit:ConfigurationEdit):Promise<ConfigurationRequest>; recreateWorker?(policy:Policy,expectedRevision?:number):Promise<Snapshot>; action(action:Action):Promise<Snapshot>; enroll(url:string,code:string):Promise<Snapshot>; fleet():Promise<Device[]>; controlDevice?(id:string,action:'pause'|'resume'|'revoke'):Promise<unknown>; createEnrollment?():Promise<{code:string;expiresAt:string}> }
export function defaultPolicy():Policy { return {enabled:false,resources:{cpus:2,memoryMib:4096,diskGib:30},idleOnly:false,idleAfterMinutes:15,allowBattery:false,minBatteryPercent:30,scheduleEnabled:false,schedule:[],startAtLogin:false,background:false,allowCi:true,allowServices:false,drainSeconds:300}; }

export type ConfigurationOperation = {type:'storagePreview';selections:StorageSelection[];options:StorageReviewOptions}|{type:'storageApply';plan:StoragePlan}|{type:'storageRecovery';enabled:boolean}|{type:'storageRetry'};
export interface ConfigurationEdit { operation?:ConfigurationOperation; requestId:string; expectedRevision:number; policy:Policy; acknowledgeInterruption:boolean }
export interface ConfigurationRequest { operation?:ConfigurationOperation|null; result?:StoragePlan|null; beforeStorage?:StorageInventory|null; effectiveStorage?:StorageInventory|null; requestId:string; status:string; actor?:string; requestedAt?:string; acknowledgedAt?:string|null; policy?:Policy; beforePolicy?:Policy; effectivePolicy?:Policy|null; effectiveResources?:Resources|null; error?:string|null }
export interface ConfigurationReport { storage?:StorageInventory|null; workerDiskLocation?:string|null; consent:boolean; revision:number; policy:Policy|null; hardware:Resources|null; allocatedResources:Resources|null; capabilities:{diskGrowth?:boolean;diskGrowthReason?:string;storage:boolean;storageReason:string;localApproval:string[]}; storageInventory:{label:string;mountPoint:string;filesystem:string;availableGib:number;configuredGib?:number;reason?:string}[]; receipts:ConfigurationRequest[] }
export interface ConfigurationView { online:boolean; report:ConfigurationReport|null; requests:ConfigurationRequest[] }
